"""
🏅 TRACK 4 — Affiliate Link Engine
מוסיף קישורי affiliate אוטומטית לבלוג ICT Blog
מייצר newsletter template + טבלת affiliate trackers

הרצה: python affiliate_engine.py
"""
import sys
from datetime import datetime
from pathlib import Path

if sys.platform == "win32":
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

OUTPUT_DIR = Path(__file__).parent / "affiliate_output"
OUTPUT_DIR.mkdir(exist_ok=True)

# ── Affiliate Programs ──────────────────────────────────────
AFFILIATE_PROGRAMS = {
    "ic_markets": {
        "name": "IC Markets",
        "url": "https://icmarkets.com/?camp=YOUR_ID",
        "commission": "CPA $200-$600 or Rebate $3-$8/lot",
        "niche": "Forex / CFD Broker",
    },
    "ftmo": {
        "name": "FTMO",
        "url": "https://ftmo.com/?affiliates=YOUR_ID",
        "commission": "10-20% of challenge fee",
        "niche": "Prop Firm",
    },
    "tradingview": {
        "name": "TradingView",
        "url": "https://www.tradingview.com/?aff_id=YOUR_ID",
        "commission": "30% recurring",
        "niche": "Charting Platform",
    },
    "blueberry": {
        "name": "Blueberry Markets",
        "url": "https://blueberrymarkets.com/?ref=YOUR_ID",
        "commission": "CPA or Rebate",
        "niche": "Forex / CFD Broker",
    },
    "amazon_books": {
        "name": "Amazon (Trading Books)",
        "url": "https://amzn.to/YOUR_TAG",
        "commission": "4-10%",
        "niche": "Trading Education Books",
    },
    "hostinger": {
        "name": "Hostinger",
        "url": "https://www.hostinger.com?REFERRALCODE=4GUBOTBIKXVG",
        "commission": "Up to $230 per referral",
        "niche": "Web Hosting / WordPress",
    },
}

# ── Newsletter Template ─────────────────────────────────────
NEWSLETTER_TEMPLATE = """שלום {name},

📊 *סיכום שבועי — {week}*

הנה האיתותים הכי טובים השבוע:

{signals_summary}

📈 *שוק השבוע:*
- DXY: {dxy}
- VIX: {vix}
- BIAS: {bias}

💡 *טיפ השבוע:* {tip}

---

🔗 *קישורים שימושיים:*
- 📊 [TradingView Chart](https://www.tradingview.com/?aff_id=YOUR_ID)
- 💰 [FTMO Challenge](https://ftmo.com/?affiliates=YOUR_ID)
- 📚 [ספרי מסחר מומלצים](https://amzn.to/YOUR_TAG)

_DYOR — Not financial advice_
"""


def generate_affiliate_links_html():
    """מייצר HTML להוספה לתחתית הפוסטים בבלוג"""
    lines = [
        "<!-- Affiliate Links — Auto-generated by affiliate_engine.py -->",
        '<div class="affiliate-box" style="background:#1e293b;border:1px solid #334155;border-radius:8px;padding:16px;margin:24px 0;">',
        '<h3 style="color:#60a5fa;margin-top:0;">🔗 Recommended Tools</h3>',
    ]

    for key, prog in AFFILIATE_PROGRAMS.items():
        lines.append(
            f'<p>'
            f'<a href="{prog["url"]}" target="_blank" rel="nofollow sponsored" '
            f'style="color:#93c5fd;text-decoration:none;">'
            f'📊 {prog["name"]}</a> — {prog["commission"]}'
            f'</p>'
        )

    lines.append('</div>')
    lines.append("<!-- End Affiliate Links -->")

    filename = OUTPUT_DIR / "affiliate_footer.html"
    filename.write_text("\n".join(lines), encoding="utf-8")
    return filename


def generate_tracker_csv():
    """מייצר טבלת מעקב affiliate"""
    filename = OUTPUT_DIR / "affiliate_tracker.csv"
    with open(filename, "w", encoding="utf-8-sig", newline="") as f:
        import csv
        writer = csv.writer(f)
        writer.writerow(["date", "program", "clicks", "signups", "revenue", "notes"])

        for key, prog in AFFILIATE_PROGRAMS.items():
            writer.writerow([
                datetime.now().strftime("%Y-%m-%d"),
                prog["name"],
                0, 0, "$0.00",
                f"Sign up at {prog['url'].split('?')[0]}",
            ])

    return filename


def generate_newsletter_archive():
    """מייצר ארכיון newsletters"""
    filename = OUTPUT_DIR / "newsletter_archive.md"

    lines = [
        "# 📧 ICT Blog Newsletter Archive",
        f"> Updated: {datetime.now().strftime('%Y-%m-%d')}",
        "",
        "## Template",
        "```",
        NEWSLETTER_TEMPLATE.strip(),
        "```",
        "",
        "## Issues",
        "| # | Date | Subject | Clicks | Revenue |",
        "|---|------|---------|--------|---------|",
        "| 1 | TBD | TBD | - | - |",
    ]

    filename.write_text("\n".join(lines), encoding="utf-8")
    return filename


def main():
    print("=" * 60)
    print("🏅 TRACK 4 — Affiliate Link Engine")
    print("=" * 60)

    programs = list(AFFILIATE_PROGRAMS.keys())
    print(f"\n📊 Affiliate Programs: {len(programs)}")
    for p in programs:
        prog = AFFILIATE_PROGRAMS[p]
        print(f"  • {prog['name']} — {prog['commission']}")

    # Generate HTML footer
    html_file = generate_affiliate_links_html()
    print(f"\n✅ Affiliate HTML Footer: {html_file}")
    print("   → העתק את התוכן ל-footer של הבלוג")

    # Generate tracker
    csv_file = generate_tracker_csv()
    print(f"✅ Affiliate Tracker CSV: {csv_file}")

    # Generate newsletter archive
    md_file = generate_newsletter_archive()
    print(f"✅ Newsletter Archive: {md_file}")

    print()
    print("📋 צעדים להפעלה:")
    print("1. הירשם לתוכניות affiliate (IC Markets, FTMO, TradingView, Blueberry)")
    print("2. עדכן YOUR_ID/YOUR_TAG בקישורים")
    print("3. העתק affiliate_footer.html לתחתית כל פוסט בבלוג")
    print("4. שלח newsletter שבועי לרשימת תפוצה")
    print(f"5. עקוב ב-affiliate_tracker.csv")
    print()
    print(f"💰 פוטנציאל: {len(programs)} תוכניות × 1-5 המרות/חודש = $200-$2,000")


if __name__ == "__main__":
    main()